/**
 * Agregados de trabajo: el camino que va de «tengo un problema o una idea» a una propuesta con
 * versiones. Todo lo de aquí es puro y encadenado, igual que el motor de decisiones.
 */

export {
  appendChained,
  chainedBody,
  type ChainedEvent,
  type ChainedInput,
  type ChainedLog,
  isChainIntact,
  verifyChain,
} from './chain.js';

export {
  type ExecutionPlan,
  executionPlanHash,
  MAX_EVIDENCE_SOURCE_LENGTH,
  MAX_EXECUTION_OBJECTIVE_LENGTH,
  MAX_SUCCESS_CRITERIA,
  MAX_SUCCESS_DESCRIPTION_LENGTH,
  MIN_EVIDENCE_SOURCE_LENGTH,
  MIN_EXECUTION_OBJECTIVE_LENGTH,
  MIN_SUCCESS_CRITERIA,
  MIN_SUCCESS_DESCRIPTION_LENGTH,
  type SuccessCriterion,
  validateExecutionPlan,
  validateExecutionPlanStructure,
} from './execution-plan.js';

export {
  acceptTaskBy,
  acceptTaskReviewBy,
  addTaskEvidenceBy,
  admitTaskCapacity,
  activateInitiative,
  applyInitiative,
  authorizeTaskDeliveryRead,
  authorizeTaskEvidenceRead,
  blockTaskBy,
  createInitiative,
  deliverTaskBy,
  type CreateInitiativeInput,
  type InitiativeActivated,
  type InitiativeByCommandMeta,
  type InitiativeCommandMeta,
  type InitiativeCreated,
  type InitiativeEvent,
  type InitiativeLog,
  type InitiativeMilestone,
  type InitiativePayload,
  type InitiativeState,
  type InitiativeStatus,
  currentInitiative,
  MAX_MILESTONE_CRITERION_LENGTH,
  MAX_TASK_DEPENDENCIES,
  MAX_TASK_EVIDENCE_PER_DELIVERY,
  MAX_TASK_EFFORT_MINUTES,
  MAX_WEEKLY_CAPACITY_MINUTES,
  type MilestonePlanned,
  MIN_EXECUTION_TITLE_LENGTH,
  MIN_MILESTONE_CRITERION_LENGTH,
  MIN_TASK_DESCRIPTION_LENGTH,
  offerTaskBy,
  OUTCOME_CRITERION_EVIDENCE,
  type OutcomeCriterionEvidence,
  planMilestoneBy,
  prepareTaskAcceptanceBy,
  rejectTaskBy,
  reofferTaskBy,
  replayInitiative,
  requestTaskChangesBy,
  requestTaskHelpBy,
  requestTaskReassignmentBy,
  resumeTaskBy,
  startTaskBy,
  type TaskAccepted,
  type TaskAcceptanceCandidate,
  type TaskBlockCategory,
  type TaskBlocked,
  TASK_BLOCK_CATEGORIES,
  type TaskCapacityAdmission,
  type TaskCapacityCheck,
  type TaskChangeReason,
  TASK_CHANGE_REASONS,
  type TaskChangesRequested,
  type TaskDelivered,
  type TaskDeliveryRecord,
  type TaskDeliveryReview,
  type TaskEvidenceAdded,
  type TaskEvidenceKindCode,
  type TaskEvidenceRecord,
  TASK_EVIDENCE_KIND_CODES,
  type TaskEvidenceSizeClass,
  TASK_EVIDENCE_SIZE_CLASSES,
  type TaskEvidenceVisibility,
  TASK_EVIDENCE_VISIBILITIES,
  type TaskHelpCategory,
  TASK_HELP_CATEGORIES,
  type TaskHelpRequested,
  type TaskHelpRequestRecord,
  type InitiativeTask,
  type TaskOffered,
  type TaskOfferRecord,
  type TaskPauseRecord,
  type TaskReassignmentRequested,
  type TaskRejected,
  type TaskReoffered,
  type TaskResumed,
  type TaskReviewAccepted,
  type TaskResponseRecord,
  type TaskResponseReason,
  TASK_RESPONSE_REASONS,
  type TaskStartRecord,
  type TaskStarted,
  type TaskStatus,
  verifyInitiativeLog,
} from './initiative.js';

export {
  type AgendaItem,
  type AgendaItemInput,
  type Agreement,
  type AgreementInput,
  applyMeeting,
  convertibleAgreements,
  convokeMeeting,
  hasRecordedAttendance,
  initialMeetingState,
  linkProposalToAgreement,
  MAX_AGENDA_ITEMS,
  MAX_AGREEMENTS,
  MAX_LOCATION_LENGTH,
  MAX_REMOTE_LINK_LENGTH,
  type MeetingCommandMeta,
  type MeetingEvent,
  type MeetingLog,
  type MeetingPayload,
  type MeetingState,
  MIN_AGENDA_ITEM_LENGTH,
  MIN_AGREEMENT_LENGTH,
  MIN_MEETING_TITLE_LENGTH,
  MIN_MINUTES_SUMMARY_LENGTH,
  publishMinutes,
  replayMeeting,
} from './meeting.js';

export {
  type CreatePrivateMaterialCommitmentInput,
  createPrivateMaterialCommitment,
  type PrivateMaterialCommitment,
  type PrivateMaterialContext,
  toPrivateMaterialCommitment,
} from './private-material.js';

export {
  applyProblem,
  attachEvidence,
  changeProblemStatus,
  EVIDENCE_CERTAINTIES,
  type EvidenceCertainty,
  type EvidenceRecord,
  initialProblemState,
  liveEvidence,
  MIN_EVIDENCE_LENGTH,
  MIN_PROBLEM_BODY_LENGTH,
  MIN_PROBLEM_TITLE_LENGTH,
  meTooCount,
  openProblem,
  type ProblemCommandMeta,
  type ProblemEvent,
  type ProblemLog,
  type ProblemPayload,
  type ProblemState,
  type ProblemStatus,
  recordMeToo,
  replayProblem,
  retractEvidence,
} from './problem.js';

export {
  amendProposal,
  applyProposal,
  currentVersion,
  draftProposal,
  initialProposalState,
  linkDecision,
  MIN_PROPOSAL_BODY_LENGTH,
  MIN_PROPOSAL_TITLE_LENGTH,
  MIN_RATIONALE_LENGTH,
  type ProposalCommandMeta,
  type ProposalEvent,
  type ProposalLog,
  type ProposalPayload,
  type ProposalState,
  type ProposalVersion,
  proposalVersionHash,
  replayProposal,
  verifyProposalLog,
  versionAt,
} from './proposal.js';

export {
  assertLedgerText,
  InvalidTextError,
  MAX_BODY_LENGTH,
  MAX_TITLE_LENGTH,
  meaningfulLength,
  normalizeLedgerText,
  type TextRules,
} from './text.js';
