/**
 * Agregados de trabajo: el camino que va de «tengo un problema o una idea» a una propuesta con
 * versiones. Todo lo de aquí es puro y encadenado, igual que el motor de decisiones.
 */

export {
  appendChained,
  chainedBody,
  type ChainedEvent,
  type ChainedInput,
  type ChainedLog,
  isChainIntact,
  verifyChain,
} from './chain.js';

export {
  type ExecutionPlan,
  executionPlanHash,
  MAX_EVIDENCE_SOURCE_LENGTH,
  MAX_EXECUTION_OBJECTIVE_LENGTH,
  MAX_SUCCESS_CRITERIA,
  MAX_SUCCESS_DESCRIPTION_LENGTH,
  MIN_EVIDENCE_SOURCE_LENGTH,
  MIN_EXECUTION_OBJECTIVE_LENGTH,
  MIN_SUCCESS_CRITERIA,
  MIN_SUCCESS_DESCRIPTION_LENGTH,
  type SuccessCriterion,
  validateExecutionPlan,
  validateExecutionPlanStructure,
} from './execution-plan.js';

export {
  acceptTaskBy,
  activateInitiative,
  applyInitiative,
  createInitiative,
  type CreateInitiativeInput,
  type InitiativeActivated,
  type InitiativeByCommandMeta,
  type InitiativeCommandMeta,
  type InitiativeCreated,
  type InitiativeEvent,
  type InitiativeLog,
  type InitiativeMilestone,
  type InitiativePayload,
  type InitiativeState,
  type InitiativeStatus,
  currentInitiative,
  MAX_MILESTONE_CRITERION_LENGTH,
  MAX_TASK_DEPENDENCIES,
  MAX_TASK_EFFORT_MINUTES,
  type MilestonePlanned,
  MIN_EXECUTION_TITLE_LENGTH,
  MIN_MILESTONE_CRITERION_LENGTH,
  MIN_TASK_DESCRIPTION_LENGTH,
  offerTaskBy,
  planMilestoneBy,
  rejectTaskBy,
  reofferTaskBy,
  replayInitiative,
  requestTaskReassignmentBy,
  type TaskAccepted,
  type InitiativeTask,
  type TaskOffered,
  type TaskOfferRecord,
  type TaskReassignmentRequested,
  type TaskRejected,
  type TaskReoffered,
  type TaskResponseRecord,
  type TaskResponseReason,
  TASK_RESPONSE_REASONS,
  type TaskStatus,
  verifyInitiativeLog,
} from './initiative.js';

export {
  applyProblem,
  attachEvidence,
  changeProblemStatus,
  EVIDENCE_CERTAINTIES,
  type EvidenceCertainty,
  type EvidenceRecord,
  initialProblemState,
  liveEvidence,
  MIN_EVIDENCE_LENGTH,
  MIN_PROBLEM_BODY_LENGTH,
  MIN_PROBLEM_TITLE_LENGTH,
  meTooCount,
  openProblem,
  type ProblemCommandMeta,
  type ProblemEvent,
  type ProblemLog,
  type ProblemPayload,
  type ProblemState,
  type ProblemStatus,
  recordMeToo,
  replayProblem,
  retractEvidence,
} from './problem.js';

export {
  amendProposal,
  applyProposal,
  currentVersion,
  draftProposal,
  initialProposalState,
  linkDecision,
  MIN_PROPOSAL_BODY_LENGTH,
  MIN_PROPOSAL_TITLE_LENGTH,
  MIN_RATIONALE_LENGTH,
  type ProposalCommandMeta,
  type ProposalEvent,
  type ProposalLog,
  type ProposalPayload,
  type ProposalState,
  type ProposalVersion,
  proposalVersionHash,
  replayProposal,
  verifyProposalLog,
  versionAt,
} from './proposal.js';

export {
  assertLedgerText,
  InvalidTextError,
  MAX_BODY_LENGTH,
  MAX_TITLE_LENGTH,
  meaningfulLength,
  normalizeLedgerText,
  type TextRules,
} from './text.js';
